config/routes.rb
Bunsho::Application.routes.draw do
  root :to => 'home#index'

  get "home/index"

  get 'documents/:uuid', :to => 'documents#show', :as => 'document_show'
  get 'documents/file/:uuid', :to => 'documents#file', :as => 'document_file'

  namespace :rest do
    post 'documents', :to => 'documents#create', :as => 'documents_create'
    get 'documents/:uuid', :to => 'documents#show', :as => 'document_show'
    get 'documents/url', :to => 'documents#url', :as => 'document_url'
  end

  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

end

app/models/document.rb
require 'open-uri'
require 'uuidtools'

class Document < ActiveRecord::Base
  attr_accessible :available_count, :downloaded_count, :drm, :mime_type, :uuid

  validates_presence_of :uuid, :mime_type
  validates :available_count, :numericality => { :only_integer => true}
  validates :downloaded_count, :numericality => { :only_integer => true}
  validates :drm, :inclusion => { :in => [true, false] }

  has_many :document_downloads, :dependent => :destroy

  before_destroy { |rec| FileUtils.rm rec.file_name, :force => true }

  scope :recent, :limit => 10, :order => 'created_at DESC'

  def initialize(*args)
    super(*args)
    self.uuid ||= UUIDTools::UUID.timestamp_create.to_s
    self.available_count ||= config.default_available_count || 5
    # Create directory for file
    FileUtils.mkdir_p(File.dirname(file_name))
  end

  def self.new_from_request(request, drm)
    document = new( :mime_type => request.media_type )
    document.drm = drm == 'true' ? true : false
    File.open(document.file_name, 'wb') do |f|
      FileUtils.copy_stream(request.body, f)
    end
    document
  end

  def self.new_from_url(url, drm)
    document = new
    document.drm = drm == 'true' ? true : false
    if document.download_url(url)
      document
    else
      document.destroy
      nil
    end
  end

  def add_available_count
    self.available_count += 1
  end

  def download_url(url)
    begin
      open(url) do |s|
        self.mime_type = s.content_type
        File.open(file_name, 'wb') { |f| FileUtils.copy_stream(s, f) }
        true
      end
    rescue OpenURI::HTTPError
      logger.info "Download #{url} failed"
      false
    end
  end

  def file_name
    File.join(config.store_dir, uuid.gsub(/^(.)(.)/, '\1/\2/'))
  end

  def can_download?
    available_count > 0 ? true : false
  end

  def downloaded(ip)
    download = DocumentDownload.create(
      :document => self,
      :downloaded_at => Time.now,
      :downloaded_from => ip
    )
    download.save
    self.available_count -= 1
    self.downloaded_count += 1
    self.save!
  end

  def to_param
    self.uuid
  end

  private

  def config
    Rails.application.config
  end

end

app/models/document_download.rb
class DocumentDownload < ActiveRecord::Base
  attr_accessible :document, :downloaded_at, :downloaded_from

  belongs_to :document

  validates_datetime :downloaded_at, :presence => true
  validates :downloaded_from, :presence => true
  validates :document, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :cas_authenticatable, :trackable

  attr_accessible :username

  validates :username, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  def show
    @document = Document.find_by_uuid(params[:uuid])
  end

  def file
    @document = Document.find_by_uuid(params[:uuid])
    if @document
      if @document.can_download?
        @document.downloaded(request.ip)
        send_file(@document.file_name, :filename => "#{@document.uuid}.pdf",
          :type => "application/pdf")
      else
        flash[:alert] = t('bunsho.document.limit_reached')
      end
    else
      flash[:alert] = t('bunsho.document.unknown')
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    url = Rails.application.config.main_service_url
    redirect_to url unless url.blank?
  end
end

app/controllers/rest/documents_controller.rb
class Rest::DocumentsController < ApplicationController
  def show
    @doc = Document.where(:uuid => params[:uuid]).first
    respond_with_doc
  end

  def create
    @doc = Document.new_from_request(request, params['drm'])
    respond_with_save
  end

  def url
    @doc = Document.new_from_url(params['url'], params['drm'])
    respond_with_save
  end

  private

  def respond_with_save
    unless @doc && @doc.save
      flash[:alert] = "Unable to create document"
    end
    respond_with_doc
  end

  def respond_with_doc
    respond_to do |format|
      format.html { render }
      format.json { render :json => @doc, :status => @doc ? 200 : 406 }
      format.text { render :text =>
                    (@doc ? document_show_url(@doc.uuid) : ''),
                    :status => (@doc ? 200 : 406) }
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/documents/show.html.erb
<div class="col-md-12">
  <div class ="row">
    <div class="col-md-12">
      <h4><%= t('bunsho.download.title') %></h4>
    </div>
  </div>

  <% if @document && @document.can_download? %>
  <div class="row">
    <div class="col-md-12">
      <%= t('bunsho.download.ready') %>
    </div>
  </div>

  <div class="row dtu-spacing">
    <div class="col-md-offset-2 col-md-10">
      <% if @document.drm %>
        <%= link_to t('bunsho.download.text'), '#', :'data-toggle' => 'modal', :'data-target' =>'#drm-fileopen-modal', :class => 'btn btn-primary' %>
      <% else %>
        <%= link_to t('bunsho.download.text'), document_file_path(@document),
            :class => 'btn btn-primary' %>
      <% end %>
      <small>(<%= t('bunsho.download.left', :count =>
        @document.available_count) %>)</small>
    </div>
  </div>

  <div class="row dtu-download-spacing">
    <div class="col-md-1">
      <b><%= t('bunsho.copyright') %></b>
    </div>
    <div class="col-md-11">
      <%= t('bunsho.copyright_text') %>
    </div>
  </div>

  <% else %>
    <% if @document %>
      <div class="row">
        <div class="col-md-12">
          <%= t('bunsho.download.no_more') %>
        </div>
      </div>
    <% else %>
      <div class="row">
        <div class="col-md-12">
          <%= t('bunsho.document.unknown') %>
        </div>
      </div>
    <% end %>
  <% end %>

  <div class="row">
    <div class="col-md-12 dtu-spacing">
      <%= t('bunsho.question') %>
      <a href="mailto:<%= t('bunsho.contact_mail') %>">
        <%= t('bunsho.contact_mail') %>
      </a>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <%= t('bunsho.contact') %>
      <a href="<%= t('bunsho.contact_url') %>">
        <%= t('bunsho.contact_url') %>
      </a>
    </div>
  </div>
</div>

<div id="drm-fileopen-modal" class="modal fade" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4>
          FileOpen-plugin required
          <a class="close pull-right" data-dismiss="modal" data-target="#drm-fileopen-modal">&times;</a>
        </h4>
      </div>
      <div class="modal-body">
        <p>The FileOpen-plugin is required to open this document, since it is protected by Digital Rights Management (DRM).</p>
        <p>Please download the plugin at <a href="http://plugin.fileopen.com/plugininstallpage.html" target="_blank">http://plugin.fileopen.com/plugininstallpage.html</a>.</p>
        <p>
          <strong>Please Notice:</strong>
          <ul>
            <li>Once opened on a particular device, the rights to that document are "attached" to that device.</li>
            <li>After initial opening of the pdf-file, you have access authorisation for 30 days – the document expire and can not be opened thereafter.</li>
            <li>You can only print the document out twice.</li>
            <li>Storage is prohibited.</li>
          </ul>
        </p>
        <p>Read more about Digital Rights Management at <a href="https://www.tib.eu/en/borrowing-ordering/tib-document-delivery/prices/licence-agreements/digital-rights-management/" target="_blank">https://www.tib.eu/en/borrowing-ordering/tib-document-delivery/prices/licence-agreements/digital-rights-management/</a></p>
      </div>
      <div class="modal-footer">
        <%= link_to t('bunsho.download.text'), document_file_path(@document),
            :class => 'btn btn-primary' %>
      </div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<h1>Document store</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en" class="no-js">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">

    <!-- Mobile viewport optimization h5bp.com/ad -->
    <meta name="HandheldFriendly" content="True">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">

    <!-- Mobile IE allows us to activate ClearType technology for smoothing fonts for easy reading -->
    <!--[if IEMobile]>
      <meta http-equiv="cleartype" content="on">
    <![endif]-->

    <title><%= t('bunsho.main.title') %></title>
    <link href="//fast.fonts.com/cssapi/5cebbbb5-be88-4802-9d8e-4388b2411419.css" media="screen" rel="stylesheet" type="text/css" />
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

  </head>
  <body>
    <%= render :partial => 'shared/header_navbar' %>

    <div id="ajax-modal" class="modal hide fade" tabindex="-1"></div>

    <!-- /container -->
    <div id="main-container" class="container">
      <!-- Top bar -->
      <div id="search-found" class="row">
      </div>
      <!-- /Top bar -->
      <div class="row">
        <div class="col-md-12">
          <div id="main-flashes">
            <%= render :partial=>'/flash_msg' %>
          </div>
        </div>
      </div>

      <div class="row">
        <%= yield %>
      </div>
    </div>

    <%= render :partial => 'shared/footer' %>
  </body>
</html>

app/views/shared/_footer.html.erb
<div id="footer">
  <%= render 'shared/service_menu' %>

  <div class="fat-footer">
    <div class="container">
      <div class="row">
        <div class="col-md-1">
          <%= link_to image_tag('dtulogo_white.png'), 'http://www.dtic.dtu.dk' %>
        </div>
        <div class="col-md-5">
          <%= t 'riyosha.footer.about_dtu_library_html', :email => "<script type=\"text/javascript\">eval(unescape('%64%6f%63%75%6d%65%6e%74%2e%77%72%69%74%65%28%27%3c%61%20%68%72%65%66%3d%22%6d%61%69%6c%74%6f%3a%64%74%69%63%40%64%74%69%63%2e%64%74%75%2e%64%6b%22%3e%64%74%69%63%40%64%74%69%63%2e%64%74%75%2e%64%6b%3c%2f%61%3e%27%29%3b'));</script>".html_safe %>
        </div>
        <div class="col-md-3 col-md-offset-3">
          <h5><%= t 'riyosha.footer.follow_us' %></h5>
          <a href="http://www.facebook.com/DTUBibliotek"><img style="margin-right: 9px" src="http://www.dtic.dtu.dk/images/modules/socialmedia/facebook.png"></a>
          <a href="http://www.youtube.com/DTUbroadcast"><img style="margin-right: 9px" src="http://www.dtic.dtu.dk/images/modules/socialmedia/youtube.png"></a>
        </div>
      </div>
    </div>
  </div>
  <div class="dtu-red-bar">
    <div class="container">
      <div class="pull-right"><a href="http://www.dtu.dk/Om-DTU/Praktisk-information/Om-dtu_dk/Cookies">About cookies</a></div>
    </div>
  </div>

</div>

app/views/shared/_header_navbar.html.erb
<div id="header-navbar-fixed-top" class="navbar navbar-fixed-top">
  <div class="level1-navbar">
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <a href="http://www.dtu.dk/english"><%= image_tag 'dtu_text_header.png' %></a>
        </div>
        <div class="col-md-6">
          <div class="pull-right">
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="clearfix"></div>
  <div class="level2-navbar hidden-xs">
    <div class="header-gradient">
      <div class="container header-gradient">
        <div class="row logos">
          <div class="col-xs-3 visible-lg">
            <%= link_to 'DTU Find<span class="dtu-red">it</span>'.html_safe, 'http://findit.dtu.dk', :class => 'findit-logo visible-desktop pull-left' %>
          </div>
          <div class="col-xs-6 login_header">
             DTU Library Document Download
          </div>
          <div class="col-xs-3">
            <%= link_to content_tag('div', '', :class => 'dtu-logo').html_safe, 'http://www.dtu.dk/english', :class => 'logo pull-right' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_service_menu.html.erb
<div class="service-menu container">
  <div class="row">
    <div class="col-md-3">
      <ul>
        <li>Find Information</li>
        <li><a href="http://www.dtic.dtu.dk/english/servicemenu/find/online">Search literature</a></li>
        <li><a href="http://libguides.dtu.dk/databases">Other search tools</a></li>
        <li><a href="http://www.dtic.dtu.dk/english/servicemenu/find/borrow">How to borrow books</a></li>
        <li><a href="http://www.dtic.dtu.dk/english/servicemenu/find/reference">Reference management</a></li>
        <li><a href="http://www.dtic.dtu.dk/english/servicemenu/find/industry_and_public">For industry and the public</a></li>
      </ul>
    </div>
    <div class="col-md-3">
      <ul>
        <li>Visit The Library</li>
        <li><a href="http://www.dtic.dtu.dk/english/servicemenu/visit/opening">Opening hours</a></li>
        <li><a href="http://www.dtic.dtu.dk/english/servicemenu/visit/exhibit">Exhibitions and events</a></li>
        <li><a href="http://www.dtic.dtu.dk/english/servicemenu/visit/innovation">Innovation environment</a></li>
        <li><a href="http://www.dtic.dtu.dk/english/servicemenu/visit/study">Study environment and IT</a></li>
        <li><a href="http://www.dtic.dtu.dk/english/servicemenu/visit/training">Training and counseling</a></li>
      </ul>
    </div>
    <div class="col-md-3">
      <ul>
        <li>Publishing At DTU</li>
        <li><a href="http://www.dtic.dtu.dk/english/servicemenu/publishing/publishing">Research publishing</a></li>
        <li><a href="http://www.dtic.dtu.dk/english/servicemenu/publishing/student">Student theses</a></li>
        <li><a href="http://www.dtic.dtu.dk/english/servicemenu/publishing/conferences">Conferences at DTU</a></li>
        <li><a href="http://www.dtic.dtu.dk/english/servicemenu/publishing/openaccess">Open access</a></li>
        <li><a href="http://www.dtic.dtu.dk/english/servicemenu/publishing/bibliometrics">Bibliometrics and ranking</a></li>
      </ul>
    </div>
    <div class="col-md-3">
      <ul>
        <li>About and Contact</li>
        <li><a href="http://www.dtic.dtu.dk/english/servicemenu/about/news_calender">News and calendar</a></li>
        <li><a href="http://www.dtic.dtu.dk/english/servicemenu/about/contact">Contact us</a></li>
        <li><a href="http://www.dtic.dtu.dk/english/servicemenu/about/staff">Staff and organisation</a></li>
        <li><a href="http://www.dtic.dtu.dk/english/servicemenu/about/mission_vision_history">Mission, vision and history</a></li>
        <li><a href="http://www.dtic.dtu.dk/english/servicemenu/about/projects">Projects and partners</a></li>
      </ul>
    </div>
  </div>
</div>